require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/recordings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Recording. As you add validations to Recording, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Recording.create! valid_attributes
      get recordings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      recording = Recording.create! valid_attributes
      get recording_url(recording)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_recording_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      recording = Recording.create! valid_attributes
      get edit_recording_url(recording)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Recording" do
        expect {
          post recordings_url, params: { recording: valid_attributes }
        }.to change(Recording, :count).by(1)
      end

      it "redirects to the created recording" do
        post recordings_url, params: { recording: valid_attributes }
        expect(response).to redirect_to(recording_url(Recording.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Recording" do
        expect {
          post recordings_url, params: { recording: invalid_attributes }
        }.to change(Recording, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post recordings_url, params: { recording: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested recording" do
        recording = Recording.create! valid_attributes
        patch recording_url(recording), params: { recording: new_attributes }
        recording.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the recording" do
        recording = Recording.create! valid_attributes
        patch recording_url(recording), params: { recording: new_attributes }
        recording.reload
        expect(response).to redirect_to(recording_url(recording))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        recording = Recording.create! valid_attributes
        patch recording_url(recording), params: { recording: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested recording" do
      recording = Recording.create! valid_attributes
      expect {
        delete recording_url(recording)
      }.to change(Recording, :count).by(-1)
    end

    it "redirects to the recordings list" do
      recording = Recording.create! valid_attributes
      delete recording_url(recording)
      expect(response).to redirect_to(recordings_url)
    end
  end
end
